### ISSUE TITLE
Thanks for the open source, is there a paper link to learn more about your system?

### ISSUE THREAD

**Issue by rookie0607** [eureka235/yolo-stutter#1]

**Comment by eureka235** [comment]
Hi @rookie0607 , our paper is still on Interspeech2024 double-blind review, we will attach a link to the paper after the review is completed.

**Comment by rookie0607** [comment]
> 你好@rookie0607，我们的论文还在Interspeech2024双盲评审中，评审完成后我们会附上论文链接。

expectation！
